# Generated by Django 4.1.3 on 2022-12-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0005_alter_cart_options_album_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Нет в наличии'),
        ),
    ]
