# Generated by Django 4.1.4 on 2022-12-09 14:01

from django.db import migrations, models
import utils.uploading


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0009_artist_description_of_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_albums', models.CharField(max_length=255, verbose_name='Альбомы музыканта')),
                ('name_of_artist', models.CharField(max_length=255, verbose_name='Имя музыканта')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.uploading.upload_function)),
            ],
            options={
                'verbose_name': 'Альбом музыканта',
                'verbose_name_plural': 'Альбомы музыканта',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='albums_of_artist',
            field=models.ManyToManyField(related_name='albums_artist', to='musicshop.albumartist', verbose_name='Альбомы артиста'),
        ),
    ]
