# Generated by Django 4.1.4 on 2022-12-09 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0010_albumartist_artist_albums_of_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumartist',
            old_name='name_of_albums',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='albumartist',
            old_name='name_of_artist',
            new_name='name',
        ),
    ]
