# Generated by Django 4.1.4 on 2022-12-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0011_rename_name_of_albums_albumartist_album_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumartist',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterField(
            model_name='albumartist',
            name='album',
            field=models.CharField(default='Альбомов нет', max_length=255, verbose_name='Альбомы музыканта'),
        ),
    ]
