# Generated by Django 4.1.4 on 2022-12-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0012_albumartist_slug_alter_albumartist_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumartist',
            name='name',
        ),
        migrations.AlterField(
            model_name='albumartist',
            name='album',
            field=models.CharField(max_length=255, verbose_name='Альбомы музыканта'),
        ),
    ]
