# Generated by Django 4.1.4 on 2022-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0013_remove_albumartist_name_alter_albumartist_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumartist',
            name='slug',
            field=models.SlugField(),
        ),
    ]
